baseURL = "http://example.org/"
languageCode = "en-us"
title = "Triathlon Club"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

# Do NOT enable auto-detection of sections for menu as it's causing duplicates
# sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Register & Join"
    url = "#"  # Changed to # so it acts as a dropdown parent
    weight = 3
    # Dropdown items for Register & Join
    [[menu.main]]
      parent = "Register & Join"
      name = "Register to race/volunteer"
      url = "https://theautomatedclub.com/MaitlandTriClub/"
      weight = 1
    [[menu.main]]
      parent = "Register & Join"
      name = "Buy season pass"
      url = "https://theautomatedclub.com/MaitlandTriClub/Enter/seasonpass20222023"
      weight = 2
    [[menu.main]]
      parent = "Register & Join"
      name = "Join MTC - Tri Aus"
      url = "https://www.triathlon.org.au/Membership/Annual_Membership.htm"
      weight = 3
  [[menu.main]]
    name = "Event Info"
    url = "/event-information/"
    weight = 4
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 5
  [[menu.main]]
    name = "Training"
    url = "/training/"
    weight = 6
  

[params]
  description = "Local triathlon club dedicated to swimming, cycling, and running"
  author = "Triathlon Club"
  images = ["images/logo.png"]
  
  # Control menu depth (how many levels to show)
  mainMenuDepth = 2